import "dotenv/config";
import esbuild from "esbuild";
import inlineWorkerPlugin from "esbuild-plugin-inline-worker";
import path from "path";
import process from "process";

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

console.log(`esbuild version = ${esbuild.version}`);

const prod = process.argv[2] === "production";

const DEFAULT_DROPBOX_APP_KEY = process.env.DROPBOX_APP_KEY || "";
const DEFAULT_ONEDRIVE_CLIENT_ID = process.env.ONEDRIVE_CLIENT_ID || "";
const DEFAULT_ONEDRIVE_AUTHORITY = process.env.ONEDRIVE_AUTHORITY || "";
const DEFAULT_REMOTELYSAVE_WEBSITE = process.env.REMOTELYSAVE_WEBSITE || "";
const DEFAULT_REMOTELYSAVE_CLIENT_ID = process.env.REMOTELYSAVE_CLIENT_ID || "";
const DEFAULT_BOX_CLIENT_ID = process.env.BOX_CLIENT_ID || "";
const DEFAULT_BOX_CLIENT_SECRET = process.env.BOX_CLIENT_SECRET || "";
const DEFAULT_PCLOUD_CLIENT_ID = process.env.PCLOUD_CLIENT_ID || "";
const DEFAULT_PCLOUD_CLIENT_SECRET = process.env.PCLOUD_CLIENT_SECRET || "";
const DEFAULT_KOOFR_CLIENT_ID = process.env.KOOFR_CLIENT_ID || "";
const DEFAULT_KOOFR_CLIENT_SECRET = process.env.KOOFR_CLIENT_SECRET || "";

esbuild
  .context({
    banner: {
      js: banner,
    },
    loader: {
      ".svg": "text",
    },
    entryPoints: ["./src/main.ts"],
    bundle: true,
    platform: "browser",
    alias: {
      "@fyears/eme": path.resolve("./libs/eme/src/index"),
      "@fyears/tsqueue": path.resolve("./libs/tsqueue/src/index"),
      "@fyears/rclone-crypt": path.resolve("./libs/rclone-crypt/src/index"),
      axios: path.resolve("./src/polyfill/axios.ts"),
      path: "path-browserify",
      stream: "stream-browserify",
      crypto: "crypto-browserify",
      buffer: "buffer",
      process: "process/browser",
      url: "url",
      util: "util",
      events: "events",
      http: "stream-http",
      https: "https-browserify",
      os: "os-browserify",
      zlib: "browserify-zlib",
      querystring: "querystring-es3",
      fs: path.resolve("./src/polyfill/empty.ts"),
      "node:url": "url",
      "node:path": "path-browserify",
      "node:stream": "stream-browserify",
      "node:buffer": "buffer",
      "node:util": "util",
      "node:events": "events",
      "node:crypto": "crypto-browserify",
      "node:http": "stream-http",
      "node:https": "https-browserify",
      "node:os": "os-browserify",
      "node:zlib": "browserify-zlib",
      "node:querystring": "querystring-es3",
      "node:process": "process/browser",
      "node:console": "console-browserify",
      "node:sqlite": path.resolve("./src/polyfill/empty.ts"),
      "node:util/types": "util",
      "node:fs": path.resolve("./src/polyfill/empty.ts"),
      "node:fs/promises": path.resolve("./src/polyfill/empty.ts"),
      "node:assert": "assert",
      "node:net": path.resolve("./src/polyfill/empty.ts"),
      "node:tls": path.resolve("./src/polyfill/empty.ts"),
      "node:dns": path.resolve("./src/polyfill/empty.ts"),
      "node:async_hooks": path.resolve("./src/polyfill/asyncHooks.ts"),
      "node:diagnostics_channel": path.resolve(
        "./src/polyfill/diagnosticsChannel.ts"
      ),
      "node:worker_threads": path.resolve("./src/polyfill/empty.ts"),
      "node:perf_hooks": path.resolve("./src/polyfill/empty.ts"),
      "node:timers": "timers-browserify",
      "stream/promises": "stream-browserify",
    },
    external: ["obsidian", "electron"],
    inject: ["./esbuild.injecthelper.mjs"],
    format: "cjs",
    target: "es2020",
    logLevel: "info",
    sourcemap: prod ? false : "inline",
    treeShaking: true,
    minify: prod,
    outfile: "main.js",
    define: {
      "global.DEFAULT_DROPBOX_APP_KEY": `"${DEFAULT_DROPBOX_APP_KEY}"`,
      "global.DEFAULT_ONEDRIVE_CLIENT_ID": `"${DEFAULT_ONEDRIVE_CLIENT_ID}"`,
      "global.DEFAULT_ONEDRIVE_AUTHORITY": `"${DEFAULT_ONEDRIVE_AUTHORITY}"`,
      "global.DEFAULT_REMOTELYSAVE_WEBSITE": `"${DEFAULT_REMOTELYSAVE_WEBSITE}"`,
      "global.DEFAULT_REMOTELYSAVE_CLIENT_ID": `"${DEFAULT_REMOTELYSAVE_CLIENT_ID}"`,
      "global.DEFAULT_BOX_CLIENT_ID": `"${DEFAULT_BOX_CLIENT_ID}"`,
      "global.DEFAULT_BOX_CLIENT_SECRET": `"${DEFAULT_BOX_CLIENT_SECRET}"`,
      "global.DEFAULT_PCLOUD_CLIENT_ID": `"${DEFAULT_PCLOUD_CLIENT_ID}"`,
      "global.DEFAULT_PCLOUD_CLIENT_SECRET": `"${DEFAULT_PCLOUD_CLIENT_SECRET}"`,
      "global.DEFAULT_KOOFR_CLIENT_ID": `"${DEFAULT_KOOFR_CLIENT_ID}"`,
      "global.DEFAULT_KOOFR_CLIENT_SECRET": `"${DEFAULT_KOOFR_CLIENT_SECRET}"`,
      global: "window",
      "process.env.NODE_DEBUG": `undefined`,
      "process.env.DEBUG": `undefined`,
    },
    plugins: [inlineWorkerPlugin()],
  })
  .then((context) => {
    if (process.argv.includes("--watch")) {
      context.watch();
    } else {
      context.rebuild().then(() => {
        context.dispose();
      });
    }
  })
  .catch(() => process.exit(1));
