# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: BuildCI

on:
  push:
    branches: ["**"]
  pull_request:
    branches: [master]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    environment: env-for-buildci

    env:
      DROPBOX_APP_KEY: ${{secrets.DROPBOX_APP_KEY}}
      ONEDRIVE_CLIENT_ID: ${{secrets.ONEDRIVE_CLIENT_ID}}
      ONEDRIVE_AUTHORITY: ${{secrets.ONEDRIVE_AUTHORITY}}
      REMOTELYSAVE_WEBSITE: ${{secrets.REMOTELYSAVE_WEBSITE}}
      REMOTELYSAVE_CLIENT_ID: ${{secrets.REMOTELYSAVE_CLIENT_ID}}

      # S3 Test Secrets
      TEST_S3_ENDPOINT: ${{secrets.TEST_S3_ENDPOINT}}
      TEST_S3_REGION: ${{secrets.TEST_S3_REGION}}
      TEST_S3_ACCESS_KEY_ID: ${{secrets.TEST_S3_ACCESS_KEY_ID}}
      TEST_S3_SECRET_ACCESS_KEY: ${{secrets.TEST_S3_SECRET_ACCESS_KEY}}
      TEST_S3_BUCKET_NAME: ${{secrets.TEST_S3_BUCKET_NAME}}
      TEST_S3_REMOTE_PREFIX: ${{secrets.TEST_S3_REMOTE_PREFIX}}

      # Dropbox Test Secrets
      TEST_DROPBOX_TOKEN: ${{secrets.TEST_DROPBOX_TOKEN}}
      TEST_DROPBOX_REMOTE_BASE_DIR: ${{secrets.TEST_DROPBOX_REMOTE_BASE_DIR}}

      # WebDAV Test Secrets
      TEST_WEBDAV_ADDRESS: ${{secrets.TEST_WEBDAV_ADDRESS}}
      TEST_WEBDAV_USERNAME: ${{secrets.TEST_WEBDAV_USERNAME}}
      TEST_WEBDAV_PASSWORD: ${{secrets.TEST_WEBDAV_PASSWORD}}

      # Internxt Test Secrets
      TEST_INTERNXT_TOKEN: ${{secrets.TEST_INTERNXT_TOKEN}}
      TEST_INTERNXT_EMAIL: ${{secrets.TEST_INTERNXT_EMAIL}}
      TEST_INTERNXT_PASSWORD: ${{secrets.TEST_INTERNXT_PASSWORD}}
      TEST_INTERNXT_MNEMONIC: ${{secrets.TEST_INTERNXT_MNEMONIC}}
      TEST_INTERNXT_BUCKET_ID: ${{secrets.TEST_INTERNXT_BUCKET_ID}}
      TEST_INTERNXT_ROOT_FOLDER_UUID: ${{secrets.TEST_INTERNXT_ROOT_FOLDER_UUID}}
      TEST_INTERNXT_REMOTE_BASE_DIR: ${{secrets.TEST_INTERNXT_REMOTE_BASE_DIR}}

    strategy:
      matrix:
        node-version: [22.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - name: Checkout codes
        uses: actions/checkout@v7
        with:
          submodules: recursive
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v7
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm install
      - name: Run library tests
        run: npm run test:libs
      - name: Run main tests
        run: npm test
      - run: npm run build
      - uses: actions/upload-artifact@v7
        with:
          name: my-dist
          path: |
            main.js
            manifest.json
            styles.css
